name: state_notifier_sample
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  provider: ^4.1.0-dev
  state_notifier: ^0.1.0+1
  flutter_state_notifier: ^0.1.0
  freezed_annotation:
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  freezed: any
  pedantic_mono:
flutter:
  uses-material-design: true